# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: event-sourcing
        path: ./src/EventSourcing/EzDomain.EventSourcing/bin/Release/net7.0/EzDomain.EventSourcing.dll
