name: Build solution

on:
  push:
    branches: [ "**" ]
    paths:
      - 'src/EventSourcing/EzDomain.EventSourcing/**'
      - 'src/EventSourcing/EzDomain.EventSourcing.EvenStores.Azure.TableStorage/**'
      
  pull_request:
    branches: [ "**" ]
    paths:
      - 'src/EventSourcing/EzDomain.EventSourcing/**'
      - 'src/EventSourcing/EzDomain.EventSourcing.EvenStores.Azure.TableStorage/**'

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build EzDomain.NET.sln

  run-unit-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Test
      run: |
        dotnet test EventSourcing/EzDomain.EventSourcing.Tests.UnitTests/EzDomain.EventSourcing.Tests.UnitTests.csproj --configuration Release --no-build --verbosity normal
        dotnet test EventSourcing/EzDomain.EventSourcing.EventStores.Azure.TableStorage.Tests.UnitTests/EzDomain.EventSourcing.EventStores.Azure.TableStorage.Tests.UnitTests.csproj --configuration Release --no-build --verbosity normal

  run-integration-test:
    runs-on: ubuntu-latest
    needs: [build]
    environment: pre-release
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Test
      run: |
        dotnet test EventSourcing/EzDomain.EventSourcing.EventStores.Azure.TableStorage.Tests.IntegrationTests/EzDomain.EventSourcing.EventStores.Azure.TableStorage.Tests.IntegrationTests.csproj --configuration Release --no-build --verbosity normal
