name: .NET

on:
  workflow_dispatch:
    branches: [ "pre-release" ]
    paths:
      - 'src/EventSourcing/EzDomain.EventSourcing/**'

defaults:
  run:
    working-directory: ./src

env:
  VERSION_PREFIX: 7.0.0
  NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

jobs:
  pack:
    runs-on: ubuntu-latest
    environment: pre-release
    steps:
    - name: Show API key
      run: echo $NUGET_API_KEY
      
