# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "pre-release", "release" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./src

env:
  VERSION_PREFIX: 7.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build EventSourcing/EzDomain.EventSourcing/EzDomain.EventSourcing.csproj --configuration Release -p:BuildNumber=${{github.run_number}}
        dotnet build EventSourcing/EzDomain.EventSourcing.Tests.UnitTests/EzDomain.EventSourcing.Tests.UnitTests.csproj --no-restore --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Test
      run: dotnet test EventSourcing/EzDomain.EventSourcing.Tests.UnitTests/EzDomain.EventSourcing.Tests.UnitTests.csproj --no-build --verbosity normal --configuration Release

  pack:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Pack pre-release
      run: dotnet pack EventSourcing/EzDomain.EventSourcing/EzDomain.EventSourcing.csproj -p:VersionPrefix=$VERSION_PREFIX --version-suffix=build.${{github.run_number}} --output ./nuget/packages --configuration Release
    - name: Pack release
      run: dotnet pack EventSourcing/EzDomain.EventSourcing/EzDomain.EventSourcing.csproj -p:VersionPrefix=$VERSION_PREFIX --output ./nuget/packages --configuration Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: EzDomain.EventSourcing
        path: |
          src/nuget/packages/EzDomain.EventSourcing.7.0.0-build.${{github.run_number}}.nupkg
          src/nuget/packages/EzDomain.EventSourcing.7.0.0.nupkg
          
  push-pre-release:
    runs-on: ubuntu-latest
    needs: [pack]
    if: github.ref == 'refs/heads/pre-release'
    environment: pre-release
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - uses: actions/download-artifact@v3
      with:
        name: EzDomain.EventSourcing.zip
    - name: Display structure of downloaded files
      run: ls -R
    - name: Push pre-release
      run: dotnet nuget push EzDomain.EventSourcing.7.0.0-build.${{github.run_number}}.nupkg -k {{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
