name: Build EzDomain.Core solution

on:
  workflow_dispatch:
    branches: [ "**" ]
    paths:
      - 'src/EzDomain.Core/**'
  push:
    branches: [ "**" ]
    paths:
      - 'src/EzDomain.Core/**'
      
  pull_request:
    branches: [ "**" ]
    paths:
      - 'src/EzDomain.Core/**'

defaults:
  run:
    working-directory: ./src

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Restore project dependencies
      run: |
        dotnet restore EzDomain.Core/EzDomain.Core.csproj
    - name: Build project
      run: |
        dotnet build EzDomain.Core/EzDomain.Core.csproj --configuration Release

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: [build-project]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Run unit tests
      run: |
        dotnet test ../tests/EzDomain.Core.Tests/EzDomain.Core.Tests.csproj --configuration Release
