name: Build EzDomain.EventStores.MongoDb solution

on:
  workflow_dispatch:
    inputs:
      runIntegrationTests:
        description: 'Run integration tests'     
        required: true
        default: 'false'
        type: boolean
    branches: [ "**" ]
    paths:
      - 'src/EzDomain.Core/EzDomain.Core.sln'
      - 'src/EzDomain.Core/**'
      - 'src/EzDomain.EventStores.MongoDb/EzDomain.EventStores.MongoDb.sln'
      - 'src/EzDomain.EventStores.MongoDb/**'
  push:
    branches: [ "**" ]
    paths:
      - 'src/EzDomain.Core/EzDomain.Core.sln'
      - 'src/EzDomain.Core/**'
      - 'src/EzDomain.EventStores.MongoDb/EzDomain.EventStores.MongoDb.sln'
      - 'src/EzDomain.EventStores.MongoDb/**'
      
  pull_request:
    branches: [ "**" ]
    paths:
      - 'src/EzDomain.Core/EzDomain.Core.sln'
      - 'src/EzDomain.Core/**'
      - 'src/EzDomain.EventStores.MongoDb/EzDomain.EventStores.MongoDb.sln'
      - 'src/EzDomain.EventStores.MongoDb/**'

defaults:
  run:
    working-directory: ./src

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Restore project dependencies
      run: |
        dotnet restore EzDomain.EventStores.MongoDb/EzDomain.EventStores.MongoDb.csproj
    - name: Build project
      run: |
        dotnet build EzDomain.EventStores.MongoDb/EzDomain.EventStores.MongoDb.csproj --configuration Release

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: [build-project]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Run unit tests
      run: |
        dotnet test ../tests/EzDomain.EventStores.MongoDb.Tests/EzDomain.EventStores.MongoDb.Tests.csproj --configuration Release --filter TestCategory=Unit

  run-integration-tests:
    runs-on: ubuntu-latest
    needs: [build-project]
    env:
      RUN_INTEGRATION_TESTS: ${{ github.event.inputs.runIntegrationTests || 'false' }}
      MONGODB_CONNECTIONSTRING: ${{ secrets.MONGODB_CONNECTIONSTRING }}
    steps:
    - name: Echo secret
      run: echo ${{ secrets.MONGODB_CONNECTIONSTRING }}
      working-directory: ./src
    - name: Echo environment variable
      run: echo ${{ env.MONGODB_CONNECTIONSTRING }}
      working-directory: ./src
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 7.0.x
    - name: Run integration tests
      if: env.RUN_INTEGRATION_TESTS == 'true'
      run: |
        dotnet test ../tests/EzDomain.EventStores.MongoDb.Tests/EzDomain.EventStores.MongoDb.Tests.csproj --configuration Release --filter TestCategory=Integration
