name: Build EzDomain.EventStores.MongoDb solution

on:
  workflow_dispatch:
    inputs:
      runIntegrationTests:
        description: 'Run integration tests'     
        required: true
        default: false
        type: boolean
    branches: [ "**" ]
    paths:
      - 'src/EzDomain.Core/**'
      - 'src/EzDomain.EventStores.MongoDb/**'
  push:
    branches: [ "**" ]
    paths:
      - 'src/EzDomain.Core/**'
      - 'src/EzDomain.EventStores.MongoDb/**'
      
  pull_request:
    branches: [ "**" ]
    paths:
      - 'src/EzDomain.Core/**'
      - 'src/EzDomain.EventStores.MongoDb/**'

defaults:
  run:
    working-directory: ./src/EzDomain.EventStores.MongoDb

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: 7.0.x
    - name: Restore project dependencies
      run: |
        dotnet restore EzDomain.EventStores.MongoDb.csproj
    - name: Build project
      run: |
        dotnet build EzDomain.EventStores.MongoDb.csproj --configuration Release

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: [build-project]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: 7.0.x
    - name: Run unit tests
      run: |
        dotnet test ../../tests/EzDomain.EventStores.MongoDb.Tests/EzDomain.EventStores.MongoDb.Tests.csproj --configuration Release --filter TestCategory=Unit

  run-integration-tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    needs: [build-project]
    env:
      RUN_INTEGRATION_TESTS: ${{ github.event.inputs.runIntegrationTests || 'false' }}
      MONGODB__CONNECTIONSTRING: ${{ secrets.MONGODB__CONNECTIONSTRING }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: 7.0.x
    - name: Run integration tests
      if: env.RUN_INTEGRATION_TESTS == 'true'
      run: |
        dotnet test ../../tests/EzDomain.EventStores.MongoDb.Tests/EzDomain.EventStores.MongoDb.Tests.csproj --configuration Release --filter TestCategory=Integration
